export const themes = [
  {
    id: 'forest',
    name: 'Forest',
    primary: '#1a3a2a',
    accent: '#c9a84c',
    bg: '#f7f5f0',
    bgGradient: '#e8f0eb',
    cardBg: '#ffffff',
    pattern: 'none',
    font: 'system',
    style: 'clean'
  },
  {
    id: 'ocean',
    name: 'Ocean',
    primary: '#1a2e4a',
    accent: '#4a9eca',
    bg: '#f0f5fa',
    bgGradient: '#d8eaf5',
    cardBg: '#ffffff',
    pattern: 'none',
    font: 'system',
    style: 'clean'
  },
  {
    id: 'rose',
    name: 'Rose',
    primary: '#4a1a2e',
    accent: '#ca4a7a',
    bg: '#faf0f3',
    bgGradient: '#f5d8e3',
    cardBg: '#ffffff',
    pattern: 'none',
    font: 'system',
    style: 'clean'
  },
  {
    id: 'midnight',
    name: 'Midnight',
    primary: '#0d0d1a',
    accent: '#7a6aca',
    bg: '#0d0d1a',
    bgGradient: '#1a1a2e',
    cardBg: 'rgba(255,255,255,0.07)',
    pattern: 'stars',
    font: 'system',
    style: 'dark',
    textColor: '#ffffff',
    subtextColor: 'rgba(255,255,255,0.6)'
  },
  {
    id: 'sand',
    name: 'Sand',
    primary: '#3a2e1a',
    accent: '#ca9a4a',
    bg: '#faf5f0',
    bgGradient: '#f5ead8',
    cardBg: '#ffffff',
    pattern: 'none',
    font: 'system',
    style: 'clean'
  },
  {
    id: 'slate',
    name: 'Slate',
    primary: '#1a2a3a',
    accent: '#4acaca',
    bg: '#f0f5f5',
    bgGradient: '#d8f0f0',
    cardBg: '#ffffff',
    pattern: 'none',
    font: 'system',
    style: 'clean'
  },
  {
    id: 'neon',
    name: 'Neon',
    primary: '#0a0a0a',
    accent: '#00ff88',
    bg: '#0a0a0a',
    bgGradient: '#111111',
    cardBg: 'rgba(0,255,136,0.05)',
    pattern: 'grid',
    font: 'mono',
    style: 'dark',
    textColor: '#00ff88',
    subtextColor: 'rgba(0,255,136,0.6)',
    borderColor: 'rgba(0,255,136,0.2)'
  },
  {
    id: 'aurora',
    name: 'Aurora',
    primary: '#0a1628',
    accent: '#64ffda',
    bg: '#0a1628',
    bgGradient: '#0a1628',
    cardBg: 'rgba(255,255,255,0.05)',
    pattern: 'aurora',
    font: 'system',
    style: 'dark',
    textColor: '#ffffff',
    subtextColor: 'rgba(255,255,255,0.6)'
  },
  {
    id: 'paper',
    name: 'Paper',
    primary: '#2c2c2c',
    accent: '#c0392b',
    bg: '#f5f0e8',
    bgGradient: '#ede8dc',
    cardBg: '#fffef9',
    pattern: 'noise',
    font: 'serif',
    style: 'vintage',
    borderColor: '#d4c9b0'
  },
  {
    id: 'glass',
    name: 'Glass',
    primary: '#1a1a2e',
    accent: '#e94560',
    bg: '#16213e',
    bgGradient: '#0f3460',
    cardBg: 'rgba(255,255,255,0.08)',
    pattern: 'glass',
    font: 'system',
    style: 'dark',
    textColor: '#ffffff',
    subtextColor: 'rgba(255,255,255,0.6)'
  },
  {
    id: 'candy',
    name: 'Candy',
    primary: '#d63384',
    accent: '#fd7e14',
    bg: '#fff0f8',
    bgGradient: '#ffe4f0',
    cardBg: '#ffffff',
    pattern: 'dots',
    font: 'rounded',
    style: 'playful',
    borderColor: '#f8b4d9'
  },
  {
    id: 'earth',
    name: 'Earth',
    primary: '#3d2b1f',
    accent: '#8b6914',
    bg: '#f2e8d9',
    bgGradient: '#e8d5ba',
    cardBg: '#fffaf4',
    pattern: 'texture',
    font: 'system',
    style: 'warm',
    borderColor: '#d4b896'
  }
]

export const getThemeById = (id) => themes.find(t => t.id === id) || themes[0]